print()
print("Задача №1 Арифметичні операції")
print()
variable_1 = 10
variable_2 = 7
print("Перше число",variable_1)
print("Друге число",variable_2)
print()
print("Сума:",variable_1 + variable_2)
print("Різниця:",variable_1 - variable_2)
print("Добуток:",variable_1 * variable_2)
print("Частка:",variable_1 / variable_2)
print()
print()
print("Задача №2 Залишок від ділення")
print()
print("Перше число",variable_1)
print("Друге число",variable_2)
print()
print("Залишок від ділення першого числа на друге:",variable_1 % variable_2)
print()
print()
print("Задача №3 Цілочисельне ділення")
print()
print("Перше число",variable_1)
print("Друге число",variable_2)
print()
print("Скільки разів перше число ділиться на друге без залишку:",variable_1 // variable_2)
print()
print()
print("Задача №4 Перетворення стрічки у число")
print()
year = int(input("Введіть свій рік народження - "))
print(year)
print(type(year))
print()
print()
print("Задача №5 Стрічкова конкатенація + математика")
print()
number_1 = input("Введіть перше число - ")
number_2 = input("Введіть друге число - ")
print(int(number_1) + int(number_2))
print(number_1 + number_2)
print()
print()
print("Задача №6 Вік користувача")
print()
year_1 = input("Введіть свій рік народження - ")
name = input("Введіть своє ім'я - ")
year_3 = input("Введіть який зараз рік - ")
print()
print("Ваше ім'я - ",name)
print("Ваш вік - ",int(year_3) - int(year_1),"років")
print()
print("Задача №7 Перевод з цельсія в фаренгейт")
print()
degree = input("Введіть кількість градусів у цельсіях - ")
print()
print("Це дорівнює кількості градусів у фарінгейтах - ",(int(degree)*9/5+32))
print()
print()
print("Задача №8 Перевод з фаренгейта в цельсій")
print()
degree = input("Введіть кількість градусів у фарінгейтах - ")
print()
print("Це дорівнює кількості градусів у цельсіях - ",(int(degree)-32)*5/9)
print()
print()
print("Задача №9 Магазин канцелярських товарів")
print()
number = input("Введіть довжину катета - ")
print()
number2 = int(number)**2 + int(number)**2
print("Довжина гіпотенузи - ",int(number2)**(1/2))
print()
print()
print("Задача №10 Школярі та яблука")
print()
number_1 = input("Введіть кількість школярів - ")
number_2 = input("Введіть кількість яблук - ")
print()
print("Кожному школяреві дістанеться порівну яблук- ",int(number_2) // int(number_1))
print("Залишок яблук в кошику - ",int(number_2) % int(number_1))
print()
print()
print("Задача №11 Магазин канцелярських товарів")
print()
number_1 = input("Скільки олівців купив Вася ? - ")
number_2 = input("Скільки ручок купив Вася ? - ")
number_3 = input("Скільки фломастерів купив Вася ? - ")
print()
print("Загальна сума канцелярських товарів - ",int(number_1)*3 + int(number_2)*5 + int(number_3)*12,"грн.")
print()
print()
